# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/168CB_sYFSto0wwapcwhVoGWV0QNnUpke
"""

import streamlit as st
from transformers import pipeline

# Load model
classifier = pipeline(
    "sentiment-analysis"
)

# Page configuration
st.set_page_config(
    page_title="AI Sentiment Analyzer",
    page_icon="🤖"
)

# Title
st.title("🤖 AI Sentiment Analyzer")

st.write(
    "Enter a sentence and the AI model "
    "will predict its sentiment."
)

# User input
text = st.text_area(
    "Enter your text:"
)

# Button
if st.button("Analyze Sentiment"):

    if text.strip():

        result = classifier(text)[0]

        label = result["label"]
        score = result["score"]

        st.subheader("Result")

        st.write(
            f"**Sentiment:** {label}"
        )

        st.write(
            f"**Confidence:** {score:.2%}"
        )

    else:

        st.warning(
            "Please enter some text."
        )

